@default_files = ('paper.tex');
$bibtex = 'bibtex %O -min-crossrefs=2000 %B';   # turn off generation of bib entries for crossref items
$pdf_mode = 1;                                   # generate pdf by default
$pdflatex = 'pdflatex -synctex=1 --shell-escape';
$clean_ext = "bbl";                              # (additional) things to remove when cleaning
